### ISSUE TITLE
ASP.NET CORE

### ISSUE THREAD

**Issue by ChrTall** [philipnewcomer/bootstrap4-card-tables#3]
Hi, I would like to use this for my Asp.net core app that ships with bootstrap4.
NPM is for Node.js I think. Is it possible to add this also to my bootstrap lib in ASP.NET CORE 3.1 ?
I used panels with tables in ASP.NET Core 2.1 with Bootstrap 3 and I would like to have a view that is like in a other project of mine.

**Comment by philipnewcomer** [comment]
There are links to ready-to-use compiled CSS files in the readme.
